### ISSUE TITLE
Error on valid input

### ISSUE THREAD

**Issue by potocpav** [PistonDevelopers/inflate#26]
This test-case fails with `Err("data stream ends without a checksum")`. The same input is parsed successfully by zlib.

```rust
#[test]
fn should_succeed() {
    let data = &[120, 156, 189, 138, 65, 13, 0, 32, 16, 195, 64, 2, 22, 176, 128, 5, 44, 96, 1, 11,
        216, 103, 19, 176, 123, 118, 73, 155, 61, 218, 155, 54, 10, 136, 192, 170, 32, 130, 41,
        249, 36, 136, 96, 73, 62, 9, 34, 216, 146, 79, 130, 8, 142, 228, 147, 32, 130, 43, 249, 36,
        136, 224, 73, 62, 9, 32, 248, 250, 192, 22, 113];
    let mut stream = inflate::InflateStream::from_zlib();
    let res = stream.update(data);
    eprintln!("res: {:?}", res);
    assert!(res.is_ok());
}
```

The problem seems to be that the [`CheckCRC` match arm](https://github.com/PistonDevelopers/inflate/blob/master/src/lib.rs#L1063) receives only the last three bytes (`[192, 22, 113]`) instead of the last four. It seems that the bit `250` is "eaten" when it should not be. When we duplicate it (the last five bytes are then `[250, 250, 192, 22, 113]`), the data stream is parsed fine.

I was unable to locate the exact issue.

**Comment by potocpav** [comment]
This also prevents the [image-png](https://github.com/PistonDevelopers/image-png) crate from upgrading to inflate 0.3, since it trips their test-case `roundtrip`.

**Comment by philipc** [comment]
The byte is lost [here](https://github.com/PistonDevelopers/inflate/blob/f7a8cd2dda5716064da863d9d58d17e11137b6db/src/lib.rs#L1004). At that point, `stream.state.n` is 8, but we discard `stream.state`.

I'm working on a fix.
