### ISSUE TITLE
Data is silently corrupted

### ISSUE THREAD

**Issue by evanw** [PistonDevelopers/inflate#38]
I have a blob of data that is 414653 bytes compressed and 1605633 bytes uncompressed. This library only decompresses 1605632 bytes (it never generates the last byte). 1605633 is 49 * 32768 + 1 so I'm guessing the bug is related to something about the buffer size, which appears to be 32768 in this library.

I uploaded the base64-encoded data as [data.txt](https://github.com/PistonDevelopers/inflate/files/1849892/data.txt) for you to use for debugging. The SHA1 of the data should be 45d4b46f3d76ae5196ff4905e9bc509c10977c11. Here's how to use it:

```
$ base64 -D data.txt > data.bin

$ shasum data.bin
45d4b46f3d76ae5196ff4905e9bc509c10977c11  data.bin

$ python -c 'import sys, zlib; print len(zlib.decompress(sys.stdin.read(), -15))' < data.bin
1605633

$ mkdir src

$ cat > Cargo.toml
[package]
name = "test"
version = "0.0.1"

[dependencies]
inflate = "0.3.4"

$ cat > src/main.rs
extern crate inflate;
use inflate::inflate_bytes;
use std::io::*;

fn main() {
  let mut input = BufReader::new(stdin());
  let mut data = vec![];
  input.read_to_end(&mut data).unwrap();
  println!("{:?}", inflate_bytes(&data).unwrap().len());
}

$ cargo build

$ cargo run < data.bin
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/test`
1605632
```

I found some other previous issues like this too. I now realize this library probably needs extensive fuzzing before it's ready to be used for real things.

**Comment by philipc** [comment]
The problem occurs when the buffer is full (so we need to return to the caller), but all remaining input data has been read into the state already.

There are two causes:
- [this check](https://github.com/PistonDevelopers/inflate/blob/49a84b542fa983d0906f33c5c96eb416fcde5c03/src/lib.rs#L1028) does not account for data that has already been read into the state
- [this loop](https://github.com/PistonDevelopers/inflate/blob/49a84b542fa983d0906f33c5c96eb416fcde5c03/src/utils.rs#L19) needs to continue until no bytes are decoded, even if there is no data remaining

**Comment by philipc** [comment]
I added some test cases and a fix for `inflate()` in https://github.com/philipc/inflate/commit/42308a35582e9911abdb7639279976bb1c14cede.

Fixing `InflateStream::update` is going to be more involved, and I'm not interested in wading through the macros to fix this one. What I think needs to be done is that `InflateStream::next_state` needs to return a bool indicating whether it made progress, and `InflateStream::update` should loop until either `next_state` returns false, or the buffer is full. The functions that read from the bit stream already return a bool, but this doesn't get carried through to the result of `next_state`. Maybe someone else has a better idea though.

**Comment by eddyb** [comment]
@philipc What about changing the loop in `update` to call `next_state` at least once?

**Comment by philipc** [comment]
@eddyb That may work, but I'll need to spend some time convincing myself that one loop is always enough to consume all the data that has been read into the state.

**Comment by philipc** [comment]
It looks to me like it also returns whenever it transitions to a new state, but maybe I am missing something.

**Comment by eddyb** [comment]
@philipc Ah, sorry, I guess you want "call `next_state` once *after* `data.len()` becomes `0`".
