### ISSUE TITLE
Is this usable, what's the API?

### ISSUE THREAD

**Issue by J-F-Liu** [PistonDevelopers/inflate#4]

**Comment by oyvindln** [comment]
It's used in the PNG crate, you can see an example of usage there: https://github.com/PistonDevelopers/image-png/blob/master/src/decoder/stream.rs#L139

This crate could probably use some documentation though.

**Comment by J-F-Liu** [comment]
I think it's better to provide a simple API, like the deflate crate.
```
use deflate::deflate_bytes;
use inflate::inflate_bytes;

let data = b"Some data";
let compressed = deflate_bytes(&data);
let decompressed = inflate_bytes(&compressed);
```
Then a decoder to work with streamed data.

**Comment by oyvindln** [comment]
Having a writer like [flate2](https://github.com/alexcrichton/flate2-rs) would also make using this library easier. 

I suppose I could implement this, it shouldn't be too complicated.
