### ISSUE TITLE
Decoder occasionally skips 2 bytes before length when decoding uncompressed block (Format error: invalid uncompressed block len)

### ISSUE THREAD

**Issue by j-tai** [PistonDevelopers/inflate#47]
I originally got this error while trying to read a large, incompressible PNG image with the `image` crate.

```rust
fn main() {
    image::open("14.png").unwrap();
}
```
[Image link](https://drive.google.com/file/d/1nckeFqgrFEp3WRvmgYQEbPuKk2gNbxGO/view?usp=sharing) (3 MB) (MD5:`15760e8fe875bbb4273df4381daae041`)

Result:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("invalid uncompressed block len: LEN: 83d9 NLEN: 3c33")', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The PNG image in question was encoded using the `image` crate itself. It can be opened in GIMP without issue, and [pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) reported no problems with the file:
```console
$ pngcheck -vt 14.png
File: 14.png (3147315 bytes)
  chunk IHDR at offset 0x0000c, length 13
    1024 x 1024 image, 24-bit RGB, non-interlaced
  chunk IDAT at offset 0x00025, length 3147258
    zlib: deflated, 32K window, default compression
  chunk IEND at offset 0x30062b, length 0
No errors detected in 14.png (3 chunks, -0.1% compression).
```

Inspecting the PNG with a hex editor, I was able to find the byte sequence `D9 83 33 3C` at offset `0x200029` in the file. It appears that the actual length was 2 bytes before that:

```yaml
200026: 00     # denotes uncompressed block
200027: 26 7C  # decoder somehow skipped these? (this is actually `len`)
200029: D9 83  # `len`:  0x83D9 (this is actually `nlen`)
20002B: 33 3C  # `nlen`: 0x3C33 (this is actually part of the block)
```

* inflate 0.4.3
* image 0.20.1
* rustc 1.31.0 (abe02cefd 2018-12-04)

**Comment by philipc** [comment]
#48 should fix this.
